export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_CATEGORYS = 'receive_categorys'
export const RECEIVE_SHOP_LIST = 'receive_shop_list'
export const RECEIVE_USER_INFO = 'receive_user_info'
export const RECEIVE_GOOD_LIST = 'receive_good_list'
export const RECEIVE_RATING_LIST = 'receive_rating_list'
export const RECEIVE_SHOP_INFO = 'receive_shop_info'
export const RECEIVE_SEARCH_SHOPS = 'receive_search_shops'

export const SET_GEOHASH = 'set_geohash'
